client_tenant:
  client_name: "<moderator_client_name>" # Client storage account name
  client_id: "<moderator_client_id>"
  client_secret: "<moderator_client_secret>"
  subscription_id: "<moderator_subscription_id>"
  tenant_id: "<moderator_tenant_id>"
parent_tenant:
  client_id: "<contributor_client_id>"
  client_secret: "<contributor_client_secret>"
  subscription_id: "<contributor_subscription_id>"
  tenant_id: "<contributor_tenant_id>"
  la_resource_group: "<contributor_log_analytics_resource_group>"
  la_storage_account: "<log_archival_storage_account>"
  la_workspace: "<contributor_log_analytics_workspace>"
